force-app/main/default/objects/Turret__c/Turret__c.object-meta.xml
<CustomObject>
    <label>Turret</label>
    <nameField>
        <label>Turret Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turrets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TurretHistory__c/TurretHistory__c.object-meta.xml
<CustomObject>
    <label>Turret History</label>
    <nameField>
        <label>TurretHistory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Turret History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TurretHistory__c/fields/Turret__c.field-meta.xml
<CustomField>
    <fullName>Turret__c</fullName>
    <label>Turret</label>
    <referenceTo>Turret__c</referenceTo>
    <relationshipLabel>Turret History</relationshipLabel>
    <relationshipName>TurretHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/TurretControllerExtension.cls
public class TurretControllerExtension {
    public Turret__c turret {get; set;}

    public TurretControllerExtension(ApexPages.StandardController stdController) {
        this.turret = (Turret__c)stdController.getRecord();
    }

    public PageReference updateTurret() {
        try {
            update turret;
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Turret has been updated');
            ApexPages.addMessage(myMsg);
        } catch(Exception e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
            ApexPages.Message errorMsg = new ApexPages.Message(ApexPages.Severity.ERROR, 'Something went wrong');
            ApexPages.addMessage(errorMsg);
        }
        return null;
    }

    public List<TurretHistory__c> getTurretRecordHistory() {
        List<TurretHistory__c> turretHistories = [
            select id,
            action__c,
            date__c,
            createdBy.name
            from TurretHistory__c
            where Turret__c = :turret.id
            order by date__c desc
            ];
            
        return turretHistories; 
    }
}