force-app/main/default/objects/Gun__c/Gun__c.object-meta.xml
<CustomObject>
    <label>Gun</label>
    <nameField>
        <label>Gun Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Guns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GunHistory__c/GunHistory__c.object-meta.xml
<CustomObject>
    <label>Gun History</label>
    <nameField>
        <displayFormat>H-{0}</displayFormat>
        <label>Gun History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Gun History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GunHistory__c/fields/Gun__c.field-meta.xml
<CustomField>
    <fullName>Gun__c</fullName>
    <label>Gun</label>
    <referenceTo>Gun__c</referenceTo>
    <relationshipName>GunHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/GunService.cls
public class GunService {    
	public static void saveChangeHistory(List<Gun__c> changedGuns) {
		List<GunHistory__c> histories = new List<GunHistory__c>();
        String historyType = 'unknown';

		if (Trigger.isInsert) {
			historyType = 'Create';
		} else if (Trigger.isUpdate) {
            historyType = 'Edit';
		} else {
			historyType = 'Delete';
		}
        
        for (Gun__c gun : changedGuns) {
            GunHistory__c history = new GunHistory__c(
                gun__c = gun.id,
                type__c = historyType,
                modifyDate__c = System.now()
			);
			histories.add(history);
        }
        
		try {
			insert histories;
		} catch (DMLException e) {
			System.debug(e);
		}
	}
}