force-app/main/default/objects/Tank__c/Tank__c.object-meta.xml
<CustomObject>
    <label>Tank</label>
    <nameField>
        <label>Tank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tanks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tank__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TanksSelector.cls
public class TanksSelector {
    public static List<Tank__c> findAll() {
        List<Tank__c> tanks = [
            select id,
            name,
            country__c
            from Tank__c
        ];
        return tanks;
    }

    public static List<Tank__c> findAllNotShared() {
        List<Tank__c> tanks = [
            select id,
            name,
            country__c
            from Tank__c
            where id not in :PartnerNetworkRecordConnectionsSelector.findAllLocalRecordIds()
        ];
        return tanks;
    }
}