force-app/main/default/objects/Tank__c/Tank__c.object-meta.xml
<CustomObject>
    <label>Tank</label>
    <nameField>
        <label>Tank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tanks</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tank__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Poland</fullName>
            </value>
            <value>
                <fullName>Germany</fullName>
            </value>
            <value>
                <fullName>US</fullName>
            </value>
            <value>
                <fullName>UK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/TankHistory__c/TankHistory__c.object-meta.xml
<CustomObject>
    <label>Tank History</label>
    <nameField>
        <displayFormat>H-{0000}</displayFormat>
        <label>Tank History Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tank History</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/TankHistory__c/fields/Tank__c.field-meta.xml
<CustomField>
    <fullName>Tank__c</fullName>
    <label>Tank</label>
    <referenceTo>Tank__c</referenceTo>
    <relationshipLabel>Tank History</relationshipLabel>
    <relationshipName>TankHistory</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/TankHistory__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Edit</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TankService.cls
public class TankService {
	public static void isDuplicate(List<Tank__c> changedTanks) {
		List<Tank__c> tanks = [
			select id,
			name,
			country__c
			from Tank__c
		];
		for (Tank__c newTank : changedTanks) {
			for (Tank__c tank : tanks) {
				if (newTank.name == tank.name && newTank.country__c == tank.country__c) {
					newTank.addError('Based on entered data possible duplicate was detected. Record not saved');
				}
			}
		}
	}
    
	public static void saveChangeHistory(List<Tank__c> changedTanks) {
		List<TankHistory__c> histories = new List<TankHistory__c>();
        String historyType = 'unknown';

		if (Trigger.isInsert) {
			historyType = 'Create';
		} else if (Trigger.isUpdate) {
            historyType = 'Edit';
		} else {
			historyType = 'Delete';
		}
        
        for (Tank__c tank : changedTanks) {
            TankHistory__c history = new TankHistory__c(
                tank__c = tank.id,
                type__c = historyType,
                modifyDate__c = System.now()
			);
			histories.add(history);
        }
        
		try {
			insert histories;
		} catch (DMLException e) {
			System.debug(e);
		}
	}
}